name: release

on: push

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Calculate slice diff
        uses: technote-space/get-diff-action@v4
        with:
          PATTERNS: |
            +(src)/**/*

      - name: Test
        run: echo 'Triggered'
        if: env.GIT_DIFF
