name: release

on: push

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Calculate slice diff
        uses: technote-space/get-diff-action@v4
        with:
          PATTERNS: |
            +(src)/**/*
  deploy:
    if: env.GIT_DIFF
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Build
        run: npm run build
